### ISSUE TITLE
Not sure if I should keep the Survival name.

### ISSUE THREAD

**Issue by dpvb** [dpvb/survival#17]
Might need other suggestions, but this could probably work for now.

**Comment by ms5984** [comment]
LGTM

**Comment by noellerjd** [comment]
Deeze

**Comment by ms5984** [comment]
Oh, what's Deeze? @noellerjd

**Comment by noellerjd** [comment]
> 

Deeze big fat balls near your lips

**Comment by dpvb** [comment]
Change to Survive.
