### ISSUE TITLE
Change abstract method to empty impl

### ISSUE THREAD

**Issue by ms5984** [dpvb/survival#19]
I like how `InventoryWrapper#handle(InventoryCloseEvent)` is implicitly defined as no-op--inheritors that have no need for it do not need to redefine it. I think we should do the same for `InventoryWrapper#handle(InventoryClickEvent)` since `InventoryWrapper` is used with `LootableChestInventory` and that class has no need for it.

**Comment by dpvb** [comment]
You want to make this change?

**Comment by ms5984** [comment]
Sure
