### ISSUE TITLE
Refactor ExtractionRegionSelector

### ISSUE THREAD

**Issue by dpvb** [dpvb/survival#21]
Currently, ExtractionRegionSelector is a Cuboid Region Selection tool, but it is made specifically for ExtractionRegion. I do not see a need to make a more general "CuboidRegion" selector, but if the need does arise this selector could use a refactor.

**Comment by ms5984** [comment]
The extraction region model is agnostic. So both the model as well as the factory util (essentially) should reflect this agnosticism with simpler name (`Region`, perhaps). The associated service is not agnostic, so that should keep its specialized name.
