### ISSUE TITLE
Control over the GameManager

### ISSUE THREAD

**Issue by dpvb** [dpvb/survival#22]
A refactor of GameManager in which an admin on the server can take down the GameManager and start it back up again on demand so that we can make changes to the Map if need be.

Could be interesting?

**Comment by ms5984** [comment]
👍

**Comment by ms5984** [comment]
Started looking into this more seriously this afternoon. Tooling up to perform this refactor I analyzed the references to this class. Most are in `GameListener`, which is perfect as `GameManager` already manages the lifecycle of the former.

The rest are in `Survival` and `Commands`, and I believe with some minor structural changes we can make this happen. Object lifecycle can still be managed statically (keep singleton) but state operations must be exposed (initialization, reset) and existing API updated to accommodate the uninitialized state (no-ops, optionals/empty collections/runtime exceptions, etc.)

**Comment by dpvb** [comment]
Resolved.
