### ISSUE TITLE
Need to control the breaking and placing of blocks.

### ISSUE THREAD

**Issue by dpvb** [dpvb/survival#25]
We do not want players to be able to break or place blocks in the Arena.

This may conflict with the EventHandler I just created in the GameListener in which it is listening for the BlockPlaceEvent regarding TNT placement and ignition.

Players that are opped (or maybe have some permission node) should be allowed to break or place blocks.

**Comment by ms5984** [comment]
New plan:
- EventHandlers set to Low priority cancels all places and breaks in hub and arena; exclude players with permission node
- Normal priority EventHandler allows TNT place in arena

**Comment by dpvb** [comment]
Should this all go inside the GameListener class?

**Comment by ms5984** [comment]
Sure

**Comment by ms5984** [comment]
Working on this now

**Comment by dpvb** [comment]
Resolved.
