### ISSUE TITLE
Custom Death Messages

### ISSUE THREAD

**Issue by dpvb** [dpvb/survival#41]
This would be neat.

@noellerjd if you want to think of Custom Death Messages that may be neat.

**Comment by ms5984** [comment]
**Implementation notes:**
So far, every Component returned by `PlayerDeathEvent#deathMessage()` has been of the subtype `TranslatableComponent`. This subinterface demands and exposes two fields: `#key` of type String and `#args` (which appears to be some manner of Component iterable--I haven't the docs in front of me at the moment).
Thus for pinning, we can `if instanceof` cast and within the `if` use the String key to match our custom messages.

**Comment by ms5984** [comment]
https://jd.adventure.kyori.net/api/4.7.0/net/kyori/adventure/text/TranslatableComponent.html
Here we are. I suspected args wasn't just Component type--indeed, the setters accept ComponentLike and expose a Component List (a simple map operation)
