### ISSUE TITLE
Ranks and text formatting.

### ISSUE THREAD

**Issue by dpvb** [dpvb/survival#55]
This is also a thing that could go outside of this project; or maybe be handled in luckperms but I'm not sure.

As far as ranks go, I just want the different ranks to have different colored names. No prefixes.

So default would be like gray or white.
Our rank would be light red or something.
Maybe a "VIP" rank that would be a diff color.

I'm sure this could be handled in luckperms, I just don't know how.

Furthermore, I want the messages to look a little different in game. Should be of this format:

{username}: {message}

Where should this be handled?

**Comment by dpvb** [comment]
I added Vault and VaultChatFormatter to the server.

Might switch the chat plugin though.

**Comment by dpvb** [comment]
Switched to LPC.

**Comment by ms5984** [comment]
> Switched to LPC.

this yeah? https://www.spigotmc.org/resources/lpc-chat-formatter-1-7-10-1-19.68965/

**Comment by ms5984** [comment]
We can implement name colors using prefixes. This is easily defined in LuckPerms. LPC will source information through Vault/LP

**Comment by ms5984** [comment]
Formatting is handled by the chat plugin, so LPC

**Comment by dpvb** [comment]
How does this resolve #45

**Comment by dpvb** [comment]
Also yeah I have it basically setup now.

Using "username-color" which acts the same exact way prefix does.
Using "message-color" for the color of the message.

**Comment by dpvb** [comment]
See LPC config.

**Comment by ms5984** [comment]
> How does this resolve #45

Fixed; non-resolved/duplicate

**Comment by dpvb** [comment]
Resolved.
