### ISSUE TITLE
Airdrop generation/spawn control

### ISSUE THREAD

**Issue by ms5984** [dpvb/survival#78]
(We have airdrops, but for now the game only supports manual spawns)

**Comment by ms5984** [comment]
I remembered two days ago we added the item that players can buy with tokens...
but yeah, anyway, did we want to try spawning them "naturally" (algo with playercount-based frequency, asserts a distance-to-nearest-player lower bound)

**Comment by dpvb** [comment]
I used the ArenaAirdropSpawnManager and included that in the GameManager class. When the game starts a task is started to run later which will spawn the airdrop.

Two things:
1) need to clean up task if its running while arena is stopping!
2) need to make it so it starts back up again after that airdrop has been spawned (i.e. the task completes).
